services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "start"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
